### ISSUE TITLE
Support Key Path Member Lookup

### ISSUE THREAD

**Issue by akkyie** [cats-oss/Unio#8]
[SE-0252](https://github.com/apple/swift-evolution/blob/master/proposals/0252-keypath-dynamic-member-lookup.md) (Key Path Member Lookup) has been implemented on Swift 5.1, and is going to be available with the next release of Xcode.

As described in the SE, it allows you to access a property of a type, using different type's KeyPath. You can return the "original" property with the KeyPath, after optionally transforming it:

```swift
// Taken from the SE
extension Lens {
  func project<U>(_ keyPath: WritableKeyPath<T, U>) -> Lens<U> {
    return Lens<U>(
        getter: { self.value[keyPath: keyPath] },
        setter: { self.value[keyPath: keyPath] = $0 })
  }
}
```

It may greatly enhance Unio's ergonomics. You will be able to write your binding inside and outside of a UnioStream, simply and type-safe (with auto-completion(!)) while keeping its unidirectional flow:
```swift
searchBar.rx.text
    .bind(to: viewStream.input.searchText)
    .disposed(by: disposeBag)

searchBar.rx.text.onNext // -> compile error
```

I hope I can make a PR with actual implementation before Swift 5.1 get released.

**Comment by marty-suzuki** [comment]
Hi!
I've released KeyPath dynamicMemberLookup supported version.
https://github.com/cats-oss/Unio/tree/0.5.0
